/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LojaSlugRouteImport } from './routes/loja.$slug'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminPlanoRouteImport } from './routes/admin.plano'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminCadastrosRouteImport } from './routes/admin.cadastros'
import { Route as LojaSlugCheckoutRouteImport } from './routes/loja.$slug.checkout'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanoRoute = AdminPlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCadastrosRoute = AdminCadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => AdminRoute,
} as any)
const LojaSlugCheckoutRoute = LojaSlugCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => LojaSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/admin/cadastros': typeof AdminCadastrosRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/plano': typeof AdminPlanoRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/loja/$slug': typeof LojaSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/loja/$slug/checkout': typeof LojaSlugCheckoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/admin/cadastros': typeof AdminCadastrosRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/plano': typeof AdminPlanoRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/loja/$slug': typeof LojaSlugRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/loja/$slug/checkout': typeof LojaSlugCheckoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/admin/cadastros': typeof AdminCadastrosRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/plano': typeof AdminPlanoRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/loja/$slug': typeof LojaSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/loja/$slug/checkout': typeof LojaSlugCheckoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/admin/cadastros'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/pedidos'
    | '/admin/plano'
    | '/admin/produtos'
    | '/admin/usuarios'
    | '/loja/$slug'
    | '/admin/'
    | '/loja/$slug/checkout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/admin/cadastros'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/pedidos'
    | '/admin/plano'
    | '/admin/produtos'
    | '/admin/usuarios'
    | '/loja/$slug'
    | '/admin'
    | '/loja/$slug/checkout'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/admin/cadastros'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/pedidos'
    | '/admin/plano'
    | '/admin/produtos'
    | '/admin/usuarios'
    | '/loja/$slug'
    | '/admin/'
    | '/loja/$slug/checkout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  LojaSlugRoute: typeof LojaSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plano': {
      id: '/admin/plano'
      path: '/plano'
      fullPath: '/admin/plano'
      preLoaderRoute: typeof AdminPlanoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cadastros': {
      id: '/admin/cadastros'
      path: '/cadastros'
      fullPath: '/admin/cadastros'
      preLoaderRoute: typeof AdminCadastrosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/loja/$slug/checkout': {
      id: '/loja/$slug/checkout'
      path: '/checkout'
      fullPath: '/loja/$slug/checkout'
      preLoaderRoute: typeof LojaSlugCheckoutRouteImport
      parentRoute: typeof LojaSlugRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCadastrosRoute: typeof AdminCadastrosRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminPlanoRoute: typeof AdminPlanoRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCadastrosRoute: AdminCadastrosRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminPlanoRoute: AdminPlanoRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LojaSlugRouteChildren {
  LojaSlugCheckoutRoute: typeof LojaSlugCheckoutRoute
}

const LojaSlugRouteChildren: LojaSlugRouteChildren = {
  LojaSlugCheckoutRoute: LojaSlugCheckoutRoute,
}

const LojaSlugRouteWithChildren = LojaSlugRoute._addFileChildren(
  LojaSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  LojaSlugRoute: LojaSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
